services:
  - type: web
    name: telegram-file-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: UPLOAD_CHANNEL_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: telegram-file-bot
          property: url
